apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: inec-ocr-app-deployment 
  labels:
    app: inec-ocr-app-deployment

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: inec-ocr-app-deployment 
  strategy: #desired strategy for replacing the unhealthy pods with new ones 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3 
  template:
    metadata:
      labels:
        app: inec-ocr-app-deployment 
    spec: 
      containers:
        - name: inec-ocr-app 
          image: similoluwaokunowo/inec-ocr-app 
          ports:
            - containerPort: 8040 
          envFrom:
            - configMapRef:
                name: inec-ocr-app-configmap 

---
apiVersion: v1 
kind: Service 
metadata:
  name: inec-ocr-app-service 
spec:
  selector:
    app: inec-ocr-app-deployment 
  type: NodePort 
  ports:
    - port: 8000 
      targetPort: 8000 
      protocol: TCP 
